#!/usr/bin/env python

if __name__ == '__main__':
    import subprocess
    debug_file = 'rcsp/parser.py'
    framework = 'pytest.py'
    opts = ''
    try:
        retcode = subprocess.check_output(['grep', 'DEBUG = False', debug_file])
        print 'Please turn ON the DEBUG switch in', debug_file, 'before testing.'
    except subprocess.CalledProcessError:
        subprocess.call(('python', framework, opts))
